### ISSUE TITLE
I am looking forward to the disclosure of the code, thank you

### ISSUE THREAD

**Issue by genbei** [CZWin32768/XLM-Align#1]
I am looking forward to the disclosure of the code, thank you

**Comment by CZWin32768** [comment]
Thanks for your interest. We have just released the model, which can be used via huggingface API. See the README for the usage. I am still working on releasing the code of XLM-Align pre-training and word alignment. Apologies for the delayed response.

**Comment by CZWin32768** [comment]
I have just created a new PR [here](https://github.com/microsoft/unilm/pull/377). So, you can find the pretraining code at [this page](https://github.com/microsoft/unilm/tree/master/infoxlm) soon.
