### ISSUE TITLE
How to use XLM-Align in word alignment task?

### ISSUE THREAD

**Issue by henryhuanghenry** [CZWin32768/XLM-Align#2]
Hello, 
I have downloaded your model from the HuggingFace. It seems that the downloaded model is a masked language model.
I am interested in using this model to do the word alignment task.
Would you mind providing me more information of how to do so ?
Looking forward to your reply!

Best wishes.

**Comment by CZWin32768** [comment]
Hi,
Thanks for your interest in our model. For word alignment self-labeling, we have released the implementation at the [InfoXLM repo](https://github.com/microsoft/unilm/tree/master/infoxlm). As for the word alignment evaluation, the code has not been released yet, but you can refer to the [code](https://github.com/microsoft/unilm/blob/f6e1cc904ce342066f152f1cfd74005008dbeaa1/infoxlm/src-infoxlm/infoxlm/tasks/xlm_align.py#L167) for word alignment self-labeling.  I will release the code for the word alignment task as soon as possible.

Thanks

**Comment by lizhiustc** [comment]
I am also interested in the word alignment evaluation . Waiting for your code ！If  preprocessing scripts will be released,  it will be an awesome  repository.

**Comment by CZWin32768** [comment]
I have released the code for word alignment evaluation. Thanks for your interest!
