### ISSUE TITLE
Missing tokens in alignment

### ISSUE THREAD

**Issue by jpcorb20** [CZWin32768/XLM-Align#3]
Hello @CZWin32768 ,

thanks a lot for the great library and model! I am interested in using your word alignment model. While testing it, I realized that some tokens were not put in the alignment for some reason. For example, I would get word alignments like:

(1, 1), (1, 2), (1, 3), (2, 4), (4, 5)

with a missing token for the third token on the left-hand side.

Would you know why some token indexes won't show up?

Thanks in advance

**Comment by CZWin32768** [comment]
This implementation follows SimAlign's argmax alignment style, which does not promise that all tokens will be aligned. It is a trade-off between precision and recall, i.e., including unconfident predictions harms precision but potentially improves recall. 

Even so, you can still find the token on the right-hand side most related to the third token on the left side, by using the similarity matrix.

**Comment by jpcorb20** [comment]
Thanks for the quick reply! Makes sense. Good to know about the similarity scores, I will check how I can implement it.
